# Generated by Django 5.0.1 on 2024-01-11 11:43
from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from apps.accounts.models import CustomUser

def create_initial_data(apps, schema_editor):
    # Create a superuser
    CustomUser.objects.create_superuser(
        email='admin@example.com',
        full_name='Admin User',
        phone_number='+265888321420',
        password='letmein',
        user_role='Admin'
    )

    # Create groups
    sales_group, created = Group.objects.get_or_create(name='Sales Team')
    managers_group, created = Group.objects.get_or_create(name='Managers Team')

    # Create permissions
    content_type = ContentType.objects.get_for_model(CustomUser)

    change_sales_data_permission, created = Permission.objects.get_or_create(
        codename='change_sales_data',
        name='Can Change Sales Data',
        content_type=content_type,
    )

    view_sales_data_permission, created = Permission.objects.get_or_create(
        codename='view_sales_data',
        name='Can View Sales Data',
        content_type=content_type,
    )

    # Assign permissions to groups
    sales_group.permissions.add(change_sales_data_permission, view_sales_data_permission)
    managers_group.permissions.add(view_sales_data_permission)

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ]
    operations = [
        migrations.RunPython(create_initial_data),
    ]