# Generated by Django 5.0.1 on 2024-01-15 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20240115_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='manufacturing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
