# Generated by Django 5.0.1 on 2024-01-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileTransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_range_start', models.FloatField()),
                ('amount_range_end', models.FloatField()),
                ('fee', models.FloatField()),
            ],
        ),
    ]
